[build]
  command = "pnpm build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-node-install"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
